name: Top Languages SVG
description: Generate top languages SVG

inputs:
  github_token:
    required: true
    description: "Repo token"
  top_n:
    required: false
    default: "5"
    description: "Number of languages"
  output_path:
    required: false
    default: "profile/top-langs.svg"
    description: "Where to output the SVG"

runs:
  using: composite
  steps:
    - name: Install dependencies
      run: |
        cd "$GITHUB_ACTION_PATH"
        npm ci
      shell: bash

    - name: Run generator
      run: |
        node "$GITHUB_ACTION_PATH/index.js"
      shell: bash
      env:
        TOP_N: ${{ inputs.top_n }}
        OUTPUT_PATH: ${{ inputs.output_path }}
        GITHUB_TOKEN: ${{ inputs.github_token }}
        WORKSPACE: ${{ github.workspace }}